Apps/golfer/urls.py
from django.urls import path

from . import views

app_name = 'golfers'

urlpatterns = [
    # ex: /home/
    path('', views.MeetTheBoard, name='MeetTheBoard'),


]

Apps/home/urls.py
from django.urls import path

from . import views

app_name = 'mga_home'

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),

]

Apps/tournaments/urls.py
from django.urls import path

from . import views

app_name = 'tournaments'

urlpatterns = [
    # ex: /tournaments/
    path('', views.tournaments, name='tournaments'),
    path('<int:tournament_id>/', views.detail, name='detail'),
    path('<int:tournament_id>/gold_tee_results/', views.gold_tee_results, name='gold_tee_results'),
    path('<int:tournament_id>/blue_tee_results/', views.blue_tee_results, name='blue_tee_results'),
    path('<int:tournament_id>/black_tee_results/', views.black_tee_results, name='black_tee_results'),
    path('<int:tournament_id>/white_tee_results/', views.white_tee_results, name='white_tee_results'),
    path('point_standings/', views.point_standings, name='point_standings'),
    path('interclub', views.interclub, name='interclub'),
]

GTWMGA/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    #path('accounts/', include('django.contrib.auth.urls')),
    path('tournaments/', include('Apps.tournaments.urls')),
    path('admin/', admin.site.urls),
    path('', include('Apps.home.urls')),
    #path('signup/', include('Apps.accounts.urls')),
    path('MeetTheBoard', include('Apps.golfer.urls')),
    path('info/', include('Apps.info.urls'))

]

Apps/home/models.py
from django.db import models

# Create your models here.

Apps/tournaments/models.py
from django.db import models
import datetime


from Apps.golfer.models import Golfer

# Create your models here.
class Tournament(models.Model):

    default_start_time = datetime.time(8,30,0)

    course = (
        ('OAKS', 'The Oaks'),
        ('PT', 'Panther Trail'),
        ('LW', 'Lake Windcrest'),
    )

    players_in_group = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
    )

    name = models.CharField(max_length=50, blank=False)
    description = models.CharField(max_length=1000, blank=False)
    date = models.DateField(blank=False)
    course = models.CharField(max_length=4, choices=course, default='OAKS')
    start_time = models.TimeField(default=default_start_time)
    gold_flight = models.BooleanField(default=True)
    blue_flight = models.BooleanField(default=True)
    white_flight = models.BooleanField(default=True)
    num_players = models.IntegerField(choices=players_in_group, default=1)
    sign_up_link = models.URLField(blank=True, null=True)
    major = models.BooleanField(default=False)
    pairing_party = models.BooleanField(default=False)
    calcutta = models.BooleanField(default=False)


    def __str__(self):
        return self.name

class Interclub(models.Model):
    date = models.DateField(blank=False)
    awayTeam = models.CharField(max_length=50, blank=True, null=True)
    homeTeam = models.CharField(max_length=50, blank=False, null=False)
    summerBreak = models.BooleanField(default=False)
    breakEnd = models.DateField(blank=True, null=True)

    class Meta:
        ordering = ('date',)

    def __str__(self):
        returnString = ""

        if self.awayTeam:
            returnString = self.awayTeam + " @ " + self.homeTeam + " | " + self.date.__str__()
        else:
            returnString = "@ " + self.homeTeam  + " | " + self.date.__str__()

        return returnString

class Point(models.Model):

    flight_color = (
        (1, "White"),
        (2, "Blue"),
        (3, "Gold"),
        (4, "Black"),
    )

    grossOrNet = (
        ('G', "Gross"),
        ('N', "Net"),
    )

    place_finished = (
        (1, "1st"),
        (2, "2nd"),
        (3, "3rd"),
        (4, "4th"),
        (99, "DNP"),
    )

    golfer = models.ForeignKey(Golfer, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    participation_points = models.IntegerField(default=100)
    extra_points = models.IntegerField(default=0, null=True, blank=True)
    flight_color = models.IntegerField(default=2, choices=flight_color, blank=False, null=False)
    flight_number = models.IntegerField(default=1, blank=False, null=False)
    date = models.DateField(default=datetime.datetime.now)
    place_finished = models.IntegerField(null=True, blank=True, default=99, choices=place_finished)
    gross_or_net = models.CharField(max_length=1, blank=False, null=False, choices=grossOrNet, default='N')

    class Meta:
        ordering = ('golfer',)

    def calc_points(self):
        points = self.participation_points

        if self.tournament.major:
            points += self.extra_points * 2
        else:
            points += self.extra_points

        return points




    def __str__(self):
        tournament_name = Tournament.objects.get(pk=self.tournament_id)
        golfer_name = Golfer.objects.get(pk=self.golfer_id)

        return golfer_name.__str__() + " - " + tournament_name.__str__() + " on " + self.date.__str__()

    def __flight_color__(key):
        if key == 1:
            return "White"
        elif key == 2:
            return "Blue"
        elif key == 3:
            return "Gold"
        else:
            return "Black"

Apps/home/views.py
from django.shortcuts import render
import datetime

from Apps.tournaments.models import Tournament

def index(request):

    tournaments = Tournament.objects.all().order_by("date")
    now = datetime.date.today()

    filteredArray = [tournament for tournament in tournaments if tournament.date > now]

    context = {}

    if filteredArray:
     context = {"tournament": filteredArray[0]}

    return render(request, 'home/index.html', context)

templates/home/index.html
{% extends 'base.html' %}


{% block content %}

    {% load static %}
    <div class="container" id="index-container">
        <div class="jumbotron">
            <h1 class="display-4 text-center">Upcoming Tournament</h1>
            {% if tournament %}

                <p class=" lead text-center" id="tournament-name">{{ tournament.name }}</p>
                <p class="text-center">{{ tournament.get_course_display }} - {{ tournament.date }}</p>
                <hr class="my-4">

                <p class="text_center" id="tournament-description">{{ tournament.description }}</p>


            <p class="lead text-center">
            {% if tournament.sign_up_link %}
                <a class="btn btn-primary btn-lg" href="{{ tournament.sign_up_link }}" role="button">Sign Up</a>
            {% endif %}
            </p>
            {% endif %}
        </div>

        <a href="{% url 'golfers:MeetTheBoard' %}" id="MeetTheBoardLink" class="home-card">
            <div class="card text-center" id="MGA-Board">
                <img src="{% static 'images/board_images/Board_Group_Photo.jpeg' %}" class="card-img-top" alt="Card Image cap">
                <div class="card-body">
                    <p class="card-text">Meet Our Board</p>
                </div>
            </div>
        </a>

        <div class="card-deck">
            <a href="#" class="home-card">
                    <div class="card h-20 text-center" style="width: 18rem;">
                        <img class="card-img-top h-50" src="{% static 'images/base_images/The-Golf-Trails-The-Woodlands-Oak-hole-15.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                        <p class="card-text">MGA Information</p>
                    </div>
                </div>
            </a>

            <a href="{% url 'tournaments:tournaments' %}" class="home-card">
                <div class="card h-20 text-center" style="width: 18rem;">
                        <img class="card-img-top h-50" src="{% static 'images/base_images/The-Golf-Trails-The-Woodlands-TX-Panther-hole-17.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                        <p class="card-text">Tournamet Schedule</p>
                    </div>
                </div>
            </a>


            <a href="{% url 'tournaments:point_standings' %}" class="home-card">
                <div class="card h-20 text-center" style="width: 18rem;">
                        <img class="card-img-top h-50" src="{% static 'images/base_images/ScoreCard.jpeg' %}" alt="Card image cap">
                        <div class="card-body">
                        <p class="card-text">Point Standings</p>
                    </div>
                </div>
            </a>

            <a href="{% url 'tournaments:interclub' %}" class="home-card">
                <div class="card h-20 text-center" style="width: 18rem;">
                        <img class="card-img-top" src="{% static 'images/base_images/The-Golf-Trails-The-Woodlands-TX-Panther-hole-17.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                        <p class="card-text">Interclub Schedule</p>
                    </div>
                </div>
            </a>

    </div>

{% endblock %}