Apps/tournaments/urls.py
from django.urls import path

from . import views

app_name = 'tournaments'

urlpatterns = [
    # ex: /tournaments/
    path('', views.tournaments, name='tournaments'),
    path('<int:tournament_id>/', views.detail, name='detail'),
    path('<int:tournament_id>/gold_tee_results/', views.gold_tee_results, name='gold_tee_results'),
    path('<int:tournament_id>/blue_tee_results/', views.blue_tee_results, name='blue_tee_results'),
    path('<int:tournament_id>/black_tee_results/', views.black_tee_results, name='black_tee_results'),
    path('<int:tournament_id>/white_tee_results/', views.white_tee_results, name='white_tee_results'),
    path('point_standings/', views.point_standings, name='point_standings'),
    path('interclub', views.interclub, name='interclub'),
]

GTWMGA/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    #path('accounts/', include('django.contrib.auth.urls')),
    path('tournaments/', include('Apps.tournaments.urls')),
    path('admin/', admin.site.urls),
    path('', include('Apps.home.urls')),
    #path('signup/', include('Apps.accounts.urls')),
    path('MeetTheBoard', include('Apps.golfer.urls')),
    path('info/', include('Apps.info.urls'))

]

Apps/tournaments/models.py
from django.db import models
import datetime


from Apps.golfer.models import Golfer

# Create your models here.
class Tournament(models.Model):

    default_start_time = datetime.time(8,30,0)

    course = (
        ('OAKS', 'The Oaks'),
        ('PT', 'Panther Trail'),
        ('LW', 'Lake Windcrest'),
    )

    players_in_group = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
    )

    name = models.CharField(max_length=50, blank=False)
    description = models.CharField(max_length=1000, blank=False)
    date = models.DateField(blank=False)
    course = models.CharField(max_length=4, choices=course, default='OAKS')
    start_time = models.TimeField(default=default_start_time)
    gold_flight = models.BooleanField(default=True)
    blue_flight = models.BooleanField(default=True)
    white_flight = models.BooleanField(default=True)
    num_players = models.IntegerField(choices=players_in_group, default=1)
    sign_up_link = models.URLField(blank=True, null=True)
    major = models.BooleanField(default=False)
    pairing_party = models.BooleanField(default=False)
    calcutta = models.BooleanField(default=False)


    def __str__(self):
        return self.name

class Interclub(models.Model):
    date = models.DateField(blank=False)
    awayTeam = models.CharField(max_length=50, blank=True, null=True)
    homeTeam = models.CharField(max_length=50, blank=False, null=False)
    summerBreak = models.BooleanField(default=False)
    breakEnd = models.DateField(blank=True, null=True)

    class Meta:
        ordering = ('date',)

    def __str__(self):
        returnString = ""

        if self.awayTeam:
            returnString = self.awayTeam + " @ " + self.homeTeam + " | " + self.date.__str__()
        else:
            returnString = "@ " + self.homeTeam  + " | " + self.date.__str__()

        return returnString

class Point(models.Model):

    flight_color = (
        (1, "White"),
        (2, "Blue"),
        (3, "Gold"),
        (4, "Black"),
    )

    grossOrNet = (
        ('G', "Gross"),
        ('N', "Net"),
    )

    place_finished = (
        (1, "1st"),
        (2, "2nd"),
        (3, "3rd"),
        (4, "4th"),
        (99, "DNP"),
    )

    golfer = models.ForeignKey(Golfer, on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    participation_points = models.IntegerField(default=100)
    extra_points = models.IntegerField(default=0, null=True, blank=True)
    flight_color = models.IntegerField(default=2, choices=flight_color, blank=False, null=False)
    flight_number = models.IntegerField(default=1, blank=False, null=False)
    date = models.DateField(default=datetime.datetime.now)
    place_finished = models.IntegerField(null=True, blank=True, default=99, choices=place_finished)
    gross_or_net = models.CharField(max_length=1, blank=False, null=False, choices=grossOrNet, default='N')

    class Meta:
        ordering = ('golfer',)

    def calc_points(self):
        points = self.participation_points

        if self.tournament.major:
            points += self.extra_points * 2
        else:
            points += self.extra_points

        return points




    def __str__(self):
        tournament_name = Tournament.objects.get(pk=self.tournament_id)
        golfer_name = Golfer.objects.get(pk=self.golfer_id)

        return golfer_name.__str__() + " - " + tournament_name.__str__() + " on " + self.date.__str__()

    def __flight_color__(key):
        if key == 1:
            return "White"
        elif key == 2:
            return "Blue"
        elif key == 3:
            return "Gold"
        else:
            return "Black"

Apps/tournaments/views.py
from django.db.models import Count, Sum
from django.shortcuts import render, get_object_or_404

import operator
import math
import datetime


from .models import Tournament, Point, Interclub
from Apps.golfer.models import Golfer

goldTeeResults = {}

# Create your views here.
def tournaments(request):
    tournament_list = Tournament.objects.order_by('date')
    context = {'tournament_list': tournament_list}
    return render(request, 'tournaments/tournaments.html', context)

def interclub(request):
    interclub_list = Interclub.objects.all()
    context = {'interclub_list': interclub_list}
    return render(request, 'tournaments/interclub.html', context)

def detail(request, tournament_id):



    tournament = get_object_or_404(Tournament, pk=tournament_id)

    black_flights = get_results(tournament_id, 4)
    gold_flights = get_results(tournament_id, 3)
    blue_flights = get_results(tournament_id, 2)
    white_flights = get_results(tournament_id, 1)

    return render(request, 'tournaments/detail.html', {'tournament': tournament, 'gold_tees':gold_flights, 'black_tees': black_flights, 'blue_tees': blue_flights, 'white_tees': white_flights })

def gold_tee_results(request, tournament_id):

    gold_tees = generate_html(get_results(tournament_id, 3))

    return render(request, 'tournaments/gold_tee_results.html', {"tournament_id":tournament_id, "gold_tees":gold_tees})
def blue_tee_results(request, tournament_id):

    blue_tees = generate_html(get_results(tournament_id, 2))

    return render(request, 'tournaments/blue_tee_results.html', {"tournament_id":tournament_id, "blue_tees":blue_tees})

def black_tee_results(request, tournament_id):
    black_tees = generate_html(get_results(tournament_id, 4))

    return render(request, 'tournaments/black_tee_results.html',
                  {"tournament_id": tournament_id, "black_tees": black_tees})

def white_tee_results(request, tournament_id):
    white_tees = generate_html(get_results(tournament_id, 1))

    return render(request, 'tournaments/white_tee_results.html',
                  {"tournament_id": tournament_id, "white_tees": white_tees})

def point_standings(request):

    points_rankings = {}
    all_golfers = Golfer.objects.all()

    for this_golfer in all_golfers:
        points = Point.objects.all().filter(golfer=this_golfer.account_id, date__year=2018)
        num_tournaments = points.count()

        sum_of_extra_points = points.aggregate(sum_of_points=Sum('extra_points'))

        participation_points = num_tournaments * 100

        if sum_of_extra_points["sum_of_points"] is not None:
            total_points_for_year = sum_of_extra_points["sum_of_points"] + participation_points
            points_rankings[this_golfer] = total_points_for_year


    sorted_points_rankings = sorted(points_rankings.items(), key=operator.itemgetter(1), reverse=True)

    ordinal = lambda n: "%d%s" % (n, "tsnrhtdd"[(n / 10 % 10 != 1) * (n % 10 < 4) * n % 10::4])
    # count for position, account for ties
    position = 1
    current_point_status = 0
    iterator = 0
    rankings = []
    for tup in sorted_points_rankings:
        # Always update the iterator
        iterator += 1

        # if the current_point status and the tup dont match, set to position to the iterator
        if tup[1] != current_point_status:
            position = iterator

        # add to the dictonary with right position
        rankings.append((tup[0], tup[1], ordinal(position), position))

        # get the current points status
        current_point_status = tup[1]

        date = datetime.datetime.now().year + 1

    return render(request, 'tournaments/point_standings.html', {"rankings":rankings, "next_year": date })

def get_results(tournament_id, tee_color):

    black_flights = {}
    gold_flights = {}
    blue_flights = {}
    white_flights = {}

    rankings = {}

    flight_details = Point.objects.values('flight_number', 'flight_color').annotate(Count('flight_number')).order_by(
        "flight_color")

    # Loop thorugh all the flight detals to determine how many of each flight there are
    for detail in flight_details:
        key_Value = str(detail['flight_color']) + "_" + str(detail['flight_number'])

        this_flight_results = Point.objects.all().filter(tournament=tournament_id, flight_color=int(key_Value[:1]),
                                                         flight_number=int(key_Value[-1:])).order_by("place_finished","-extra_points","gross_or_net",
                                                                                                      "golfer__last_name")

        rankings[key_Value] = this_flight_results

    # set each tee group into their own dictionary
    for key, value in rankings.items():
        if int(key[0]) == 4:
            black_flights[key[2]] = value

        if int(key[0]) == 3:
            gold_flights[key[2]] = value

        if int(key[0]) == 2:
            blue_flights[key[2]] = value

        if int(key[0]) == 1:
            white_flights[key[2]] = value


    if tee_color ==4:
        return black_flights
    elif tee_color ==3:
        return gold_flights
    elif tee_color ==2:
        return blue_flights
    else:
        return white_flights


def generate_html(resultsDict):

    returnHtml = ""

    for key, value in resultsDict.items():
        returnHtml += '<h4 class="text-center"><strong>Flight ' + key + ' </strong></h4>\n'
        returnHtml += '\t\t<table class="table-hover table table-bordered">\n'
        returnHtml += '\t\t\t<thead>\n'
        returnHtml += '\t\t\t\t<tr>\n'
        returnHtml += '\t\t\t\t\t<th scope="col">Place</th>\n'
        returnHtml += '\t\t\t\t\t<th scope="col">Gross</th>\n'
        returnHtml += '\t\t\t\t\t<th scope="col">Name</th>\n'
        returnHtml += '\t\t\t\t\t<th scope="col">Divison</th>\n'
        returnHtml += '\t\t\t\t\t<th scope="col">Points Awarded</th>\n'
        returnHtml += '\t\t\t</tr>\n'
        returnHtml += '\t\t\t</thead>\n'
        returnHtml += '\t\t\t<tbody>\n'

        for golfer in value:
            returnHtml += '\t\t\t\t<tr>\n'
            returnHtml += '\t\t\t\t\t<td>' + str(golfer.get_place_finished_display()) + '</td>\n'
            returnHtml += '\t\t\t\t\t<td>' + str(golfer.get_gross_or_net_display()) + '</td>\n'
            returnHtml += '\t\t\t\t\t<td>' + str(golfer.golfer) + '</td>\n'
            returnHtml += '\t\t\t\t\t<td>' + str(golfer.get_flight_color_display()) + '</td>\n'
            returnHtml += '\t\t\t\t\t<td>' + str(golfer.calc_points()) + '</td>\n'
            returnHtml += '\t\t\t\t<tr>\n'

        returnHtml += '\t\t\t<tbody>\n'
        returnHtml += '\t\t</table>\n'

    return returnHtml

templates/tournaments/black_tee_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container results-container">
        {{ black_tees|safe }}
    </div>
{% endblock %}

templates/tournaments/blue_tee_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container results-container">
        {{ blue_tees|safe }}
    </div>
{% endblock %}

templates/tournaments/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
            <div class="jumbotron detail-jumbotron">
                <div class="container">
                    <h1 class="display-3 text-center">{{ tournament.name }}</h1>
                    <p class="lead text-center">{{ tournament.description }}</p>
                    <hr class="my-5">
                    <p class="text-center" style="font-size: 40px;">{{ tournament.date }} | {{ tournament.get_course_display }}</p>
                </div>
            </div>

            <div class="card-deck">
                {% if black_tees.1 %}
                    <a href="{% url 'tournaments:black_tee_results' tournament_id=tournament.id %}" class="home-card">
                        <div class="card" style="width: 20rem; height: 5rem; background-color: black; color: white">
                            <h5 class="card-header text-center">Black Tees (Championship)</h5>
                            <p class="card-text text-center">Results</p>
                        </div>
                    </a>
                {% endif %}

                {% if gold_tees.1 %}
                    <a href="{% url 'tournaments:gold_tee_results' tournament_id=tournament.id %}" class="home-card">
                        <div class="card" style="width: 20rem; height: 5rem; background-color: gold;">
                            <h5 class="card-header text-center">Gold Tees {% if not black_tees %}(Championship) {% endif %}</h5>
                            <p class="card-text text-center">Results</p>
                        </div>
                    </a>
                {% endif %}

                {% if blue_tees.1 %}
                    <a href="{% url 'tournaments:blue_tee_results' tournament_id=tournament.id %}" class="home-card">
                        <div class="card" style="width: 20rem; height: 5rem; background-color: deepskyblue;">
                            <h5 class="card-header text-center">Blue Tees</h5>
                            <p class="card-text text-center">Results</p>
                        </div>
                    </a>
                {% endif %}

                {% if white_tees.1 %}
                    <a href="{% url 'tournaments:white_tee_results' tournament_id=tournament.id %}" class="home-card">
                        <div class="card" style="width: 20rem; height: 5rem;">
                            <h5 class="card-header text-center">White Tees</h5>
                            <p class="card-text text-center">Results</p>
                        </div>
                    </a>
                {% endif %}
        </div>
    </div>

{% endblock %}

templates/tournaments/gold_tee_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container results-container">
        {{ gold_tees|safe }}
    </div>
{% endblock %}

templates/tournaments/interclub.html
{% extends 'base.html' %}

{% block content %}
    {% if interclub_list %}

    <div class="container" id="interclub-container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Location</th>
                </tr>
            </thead>
            <tbody>
                {% for event in interclub_list %}

                    <tr>
                        {% if event.breakEnd %}
                            <td>{{ event.date }} - {{ event.breakEnd }}</td>
                        {% else %}
                            <td>{{ event.date }}</td>
                        {% endif %}

                        {% if event.awayTeam %}
                            <td>{{ event.awayTeam }} @ {{ event.homeTeam }}</td>
                        {% elif event.breakEnd %}
                            <td>Summer Break, Make Up Matches Only</td>
                        {% else %}
                            <td>@ {{ event.homeTeam }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    {% endif %}

{% endblock %}

templates/tournaments/point_standings.html
{% extends 'base.html' %}

{% block content %}
    <div class="container points-container">

        <h2 class="text-center" style="margin-top: 20px;"> Top 34 and Ties After The Front Tee Fiasco in December Qualify for The Cup in March {{ next_year }} (Highlighted in Yellow)</h2>
        <table class="table table-bordered table-hover" id="points-table">
            <thead>
            <tr>
                <th scope="col">Position</th>
                <th scope="col">Points</th>
                <th scope="col">Golfer</th>
            </tr>
            </thead>
            <tbody>
                {% for golfer_tup in rankings %}

                <tr {% if golfer_tup.3 <= 34 %} class="cup-qualifier" {% endif %}>
                    <td>{{ golfer_tup.2 }}</td>
                    <td>{{ golfer_tup.1 }}</td>
                    <td>{{ golfer_tup.0 }}</td>

                </tr>



                {% endfor %}
            </tbody>

        </table>

    </div>

{% endblock %}

templates/tournaments/tournaments.html
{% extends 'base.html' %}

{% block content %}

{% if tournament_list %}
    <div class="container" id="tournament-container">
        <table class="table-hover table">
            <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Course</th>
                    <th scope="col">Tournament</th>
                </tr>
            </thead>
            <tbody>
                {% for tournament in tournament_list %}
                    <tr>
                        <td><a href='{% url "tournaments:detail" tournament.id %}'>{{ tournament.date }}</a></td>
                        <td>{{ tournament.get_course_display }}</td>
                        <td>{{ tournament.name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <p>To Tournaments Availible at this Time</p>
{% endif %}

{% endblock %}

templates/tournaments/tournamets.html
{% extends 'base.html' %}

{% block content %}

{% if tournament_list %}
    <div class="container" id="tournament-container">
        <table class="table-hover table">
            <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Course</th>
                    <th scope="col">Tournament</th>
                </tr>
            </thead>
            <tbody>
                {% for tournament in tournament_list %}
                    <tr>
                        <td><a href="{% url 'tournaments:detail' tournament.id %}">{{ tournament.date }}</a></td>
                        <td>{{ tournament.get_course_display }}</td>
                        <td>{{ tournament.name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <p>To Tournaments Availible at this Time</p>
{% endif %}

{% endblock %}

templates/tournaments/white_tee_results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container results-container">
        {{ white_tees|safe }}
    </div>
{% endblock %}