Apps/golfer/urls.py
from django.urls import path

from . import views

app_name = 'golfers'

urlpatterns = [
    # ex: /home/
    path('', views.MeetTheBoard, name='MeetTheBoard'),


]

GTWMGA/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    #path('accounts/', include('django.contrib.auth.urls')),
    path('tournaments/', include('Apps.tournaments.urls')),
    path('admin/', admin.site.urls),
    path('', include('Apps.home.urls')),
    #path('signup/', include('Apps.accounts.urls')),
    path('MeetTheBoard', include('Apps.golfer.urls')),
    path('info/', include('Apps.info.urls'))

]

Apps/golfer/models.py
from django.db import models
from Apps.accounts.models import MyUser
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Golfer(models.Model):

    board_choices = (
        (0, 'Non Board Member'),
        (1, 'Board Member'),
        (2, 'Treasurer'),
        (3, 'Tournament Chairman'),
        (4, 'Secretary'),
        (5, 'Website Admin'),
        (6, 'Handicap Chairman'),
        (7, 'Vice President'),
        (8, 'President')
    )

    account = models.OneToOneField(MyUser, primary_key=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40, blank=False, null=True)
    last_name = models.CharField(max_length=60, blank=False, null=True)
    ghin_number = models.CharField(max_length=10, blank=True, null=True)
    handicap = models.DecimalField(blank=True, null=True, decimal_places=1, max_digits=3)
    board_member = models.IntegerField(blank=False, null=False, default=0, choices=board_choices)
    board_member_photo = models.CharField(blank=True, max_length=255, null=True)

    class Meta:
        ordering = ('last_name',)

    @receiver(post_save, sender=MyUser)
    def create_user(sender, instance, created, **kwargs):
        if created:
            Golfer.objects.create(account=instance)

    @receiver(post_save, sender=MyUser)
    def save_user(sender, instance, **kwargs):
        instance.golfer.save()

    def __str__(self):

        returnString= "Profile Not Set"

        if self.last_name:
            returnString = "{lastName}, {firstName}".format(firstName=self.first_name, lastName=self.last_name)

        return returnString

Apps/golfer/views.py
from django.shortcuts import render

from .models import Golfer

# Create your views here.
def MeetTheBoard(request):
    board_member_list = Golfer.objects.all().filter(board_member__gt=0).order_by('-board_member')
    context = {'board_member_list': board_member_list}
    return render(request,'golfers/MeetTheBoard.html',context)

templates/golfers/MeetTheBoard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="container" id="board-container" style="width: 40rem;">
    <div class="container board-header">
        <p class="text-center"><strong>MGA Officers and Board</strong></p>
    </div>
    {% for board_member in board_member_list %}
        <div class="card Board-Card text-center" >
            <img src="{% static board_member.board_member_photo %}"  alt="">
            <div class="card-body">
                <p class="card-text">{{ board_member.first_name }} {{ board_member.last_name }}</p>
            </div>
            <div class="card-footer">
                {{ board_member.get_board_member_display }}
            </div>
        </div>
    {% endfor %}
</div>




{% endblock %}