Apps/golfer/urls.py
from django.urls import path

from . import views

app_name = 'golfers'

urlpatterns = [
    # ex: /home/
    path('', views.MeetTheBoard, name='MeetTheBoard'),


]

Apps/home/urls.py
from django.urls import path

from . import views

app_name = 'mga_home'

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),

]

Apps/info/urls.py
from django.urls import path

from . import views

app_name = 'info'

urlpatterns = [
    # ex: /home/
    path('bylaws/', views.bylaws, name='ByLaws'),


]

Apps/tournaments/urls.py
from django.urls import path

from . import views

app_name = 'tournaments'

urlpatterns = [
    # ex: /tournaments/
    path('', views.tournaments, name='tournaments'),
    path('<int:tournament_id>/', views.detail, name='detail'),
    path('<int:tournament_id>/gold_tee_results/', views.gold_tee_results, name='gold_tee_results'),
    path('<int:tournament_id>/blue_tee_results/', views.blue_tee_results, name='blue_tee_results'),
    path('<int:tournament_id>/black_tee_results/', views.black_tee_results, name='black_tee_results'),
    path('<int:tournament_id>/white_tee_results/', views.white_tee_results, name='white_tee_results'),
    path('point_standings/', views.point_standings, name='point_standings'),
    path('interclub', views.interclub, name='interclub'),
]

GTWMGA/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    #path('accounts/', include('django.contrib.auth.urls')),
    path('tournaments/', include('Apps.tournaments.urls')),
    path('admin/', admin.site.urls),
    path('', include('Apps.home.urls')),
    #path('signup/', include('Apps.accounts.urls')),
    path('MeetTheBoard', include('Apps.golfer.urls')),
    path('info/', include('Apps.info.urls'))

]

templates/components/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-static-top">
    <div class="container">
          <a class="navbar-brand" href="{% url 'mga_home:index' %}" style="color: gold;">Golf Trails of the Woodlands Member Golf Association</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <span class="mr-auto"></span>

              <a href="{% url 'tournaments:tournaments' %}" class="nav-link text-center">Tournaments<span class="sr-only">(current)</span></a>
              <a href="{% url 'tournaments:point_standings' %}" class="nav-link text-center">Points<span class="sr-only">(current)</span></a>
              <a href="{% url 'golfers:MeetTheBoard' %}" class="nav-link text-center">Board<span class="sr-only">(current)</span></a>
              <a href="{% url 'info:ByLaws' %}" class="nav-link text-center">ByLaws<span class="sr-only">(current)</span></a>
          </div>
    </div>

</nav>